### ISSUE TITLE
Support pipenv

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3270]
This is a placeholder for supporting `pipenv` in Pyramid. Please add to it.

* Really good article about pipenv: https://realpython.com/pipenv-guide/

## Questions

1. [How and where to install `pipenv`](https://docs.pipenv.org/install/)?
2. Where does installation of `pipenv` fit into our [current installation documentation](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html)?
3. Are there any features of `pipenv` that we would use beside installation of packages and distribution of an app?
4. What would happen to the environment variable `$VENV` in most of our commands?

## Things to update

1. Documentation wherever `pip` is used.
2. Pyramid's packaging related files, including `setup.py`.
3. Pyramid cookiecutters.

**Comment by mmerickel** [comment]
The main issue I have seen in my experience using pipenv is that it doesn't mix very cleanly with a `setup.py`. It's possible but you run into questions about where to define the dependencies. I have one project where the `Pipfile` is literally just a shim pointing to the `setup.py` where all the deps were declared. This works pretty well actually but it does feel odd.

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = "3.6.5"

[packages]
myapp = {path = ".", editable = true}

[dev-packages]
myapp = {path = ".", extras = ["testing"], editable = true}
```

The workflow here is to basically edit `setup.py` and then run `pipenv lock` which updates `Pipfile.lock` and you never really change the `Pipfile`.

The **main** reasons why we use `setup.py` in our projects is for `console_scripts` and `paster.app_factory` entry points. If a) python had a better way to define entry points, or b) if we were less dependent on them, then we could probably embrace pipenv a little bit more cleanly.
